import 'models.dart';

const products = <Product>[
  Product(
    id: ProductId('arc-lamp'),
    name: 'Arc desk lamp',
    tagline: 'Warm light, focused work.',
    description:
        'A dimmable aluminum lamp with touch controls and a soft, flicker-free glow.',
    price: 89,
    category: Category.workspace,
    image: 'assets/products/arc-lamp.jpg',
    color: 0xFFF3D9A4,
    rating: 4.8,
    isNew: true,
  ),
  Product(
    id: ProductId('halo-speaker'),
    name: 'Halo speaker',
    tagline: 'Room-filling sound, quietly designed.',
    description:
        'A compact wireless speaker tuned for detailed sound and all-day listening.',
    price: 129,
    category: Category.audio,
    image: 'assets/products/090f5442-a2e7-4cdf-a227-1f2eff9e310b.webp',
    color: 0xFFC8D8D2,
    rating: 4.9,
  ),
  Product(
    id: ProductId('cloud-headphones'),
    name: 'Cloud headphones',
    tagline: 'Your quiet place, anywhere.',
    description:
        'Lightweight over-ear headphones with adaptive noise cancellation.',
    price: 249,
    category: Category.audio,
    image: 'assets/products/cloud-headphone.jpg',
    color: 0xFFD8D0E8,
    rating: 4.7,
    isNew: true,
  ),
  Product(
    id: ProductId('field-bottle'),
    name: 'Field bottle',
    tagline: 'Cold for 24 hours. Clean forever.',
    description:
        'A double-wall steel bottle with a ceramic-lined interior and carry loop.',
    price: 38,
    category: Category.lifestyle,
    image: 'assets/products/bottle.jpg',
    color: 0xFFBAD7E8,
    rating: 4.6,
  ),
  Product(
    id: ProductId('orbit-keyboard'),
    name: 'Orbit keyboard',
    tagline: 'A better rhythm for every day.',
    description:
        'A low-profile mechanical keyboard with tactile switches and wireless pairing.',
    price: 159,
    category: Category.workspace,
    image: 'assets/products/orbit-keyboard.jpg',
    color: 0xFFE3C8B6,
    rating: 4.9,
  ),
  Product(
    id: ProductId('fold-tote'),
    name: 'Fold tote',
    tagline: 'Carries more. Packs down small.',
    description:
        'A water-resistant everyday tote made from recycled ripstop fabric.',
    price: 54,
    category: Category.lifestyle,
    image: 'assets/products/brando-makes-branding-smTDI-z1rlY-unsplash.jpg',
    color: 0xFFD7D7B8,
    rating: 4.5,
  ),
  Product(
    id: ProductId('macbook'),
    name: 'Macbook',
    tagline: 'Laptop',
    description: 'High tech and compact laptop',
    price: 54,
    category: Category.lifestyle,
    image: 'assets/products/macbook.jpg',
    color: 0xFFD7D7B8,
    rating: 4.5,
  ),
  Product(
    id: ProductId('canvas-backpack'),
    name: 'Canvas backpack',
    tagline: 'Ready for the everyday.',
    description:
        'A durable canvas backpack with a padded laptop compartment and adjustable straps.',
    price: 78,
    category: Category.lifestyle,
    image: 'assets/products/canvas-backpack.jpg',
    color: 0xFFC8D5C0,
    rating: 4.7,
  ),
  Product(
    id: ProductId('ceramic-bottle'),
    name: 'Ceramic bottle',
    tagline: 'Clean taste. Calm design.',
    description:
        'A reusable ceramic-lined bottle that keeps drinks fresh throughout the day.',
    price: 36,
    category: Category.lifestyle,
    image: 'assets/products/ceramic-bottle.jpg',
    color: 0xFFE6D8CB,
    rating: 4.3,
  ),
  Product(
    id: ProductId('travel-pouch'),
    name: 'Travel pouch',
    tagline: 'Small essentials, sorted.',
    description:
        'A compact organizer with multiple pockets for cables, toiletries, and daily essentials.',
    price: 29,
    category: Category.lifestyle,
    image: 'assets/products/travel-pouch.jpg',
    color: 0xFFCED9E5,
    rating: 4.4,
  ),
  Product(
    id: ProductId('linen-cap'),
    name: 'Linen cap',
    tagline: 'Light shade for sunny days.',
    description:
        'A breathable linen cap with an adjustable back strap and soft cotton lining.',
    price: 32,
    category: Category.lifestyle,
    image: 'assets/products/linen-cap.jpg',
    color: 0xFFE9D9B4,
    rating: 4.2,
  ),
  Product(
    id: ProductId('weekend-duffel'),
    name: 'Weekend duffel',
    tagline: 'Pack light. Go farther.',
    description:
        'A spacious recycled-fabric duffel with reinforced handles and a removable shoulder strap.',
    price: 96,
    category: Category.lifestyle,
    image: 'assets/products/weekend-duffel.jpg',
    color: 0xFFBFC8B8,
    rating: 4.8,
  ),
  Product(
    id: ProductId('wool-throw'),
    name: 'Wool throw',
    tagline: 'Warmth without the weight.',
    description:
        'A soft woven throw made from a warm recycled-wool blend with finished edges.',
    price: 84,
    category: Category.lifestyle,
    image: 'assets/products/wool-throw.jpg',
    color: 0xFFD8C4B6,
    rating: 4.6,
  ),
  Product(
    id: ProductId('desk-organizer'),
    name: 'Desk organizer',
    tagline: 'A calmer place to work.',
    description:
        'A minimal organizer with dedicated spaces for stationery, notes, and small devices.',
    price: 42,
    category: Category.lifestyle,
    image: 'assets/products/desk-organizer.jpg',
    color: 0xFFD5CBBE,
    rating: 4.1,
  ),
  Product(
    id: ProductId('compact-umbrella'),
    name: 'Compact umbrella',
    tagline: 'Rain-ready, pocket-sized.',
    description:
        'A lightweight wind-resistant umbrella with an automatic open-and-close mechanism.',
    price: 39,
    category: Category.lifestyle,
    image: 'assets/products/compact-umbrella.jpg',
    color: 0xFFBCCBD3,
    rating: 4.5,
  ),
  Product(
    id: ProductId('everyday-wallet'),
    name: 'Everyday wallet',
    tagline: 'Slim profile. Plenty of room.',
    description:
        'A compact vegan-leather wallet with card slots, a cash pocket, and secure closure.',
    price: 48,
    category: Category.lifestyle,
    image: 'assets/products/everyday-wallet.jpg',
    color: 0xFFD0B7A5,
    rating: 4.4,
  ),
];
